/* test_p11rv_mapping.c — Full coverage of P11RvToSecStatus()
 * Tests all CK_RV codes listed in p11_utils.c plus edge cases.
 */
#include "../mock/windows_compat.h"
#include "../../src/pkcs11/pkcs11.h"
#include "test_framework.h"

/* On inclut directement la fonction (pas de LinkLibrary sur Linux) */
SECURITY_STATUS P11RvToSecStatus(CK_RV rv);

/* ── Stub minimal pour compiler p11_utils.c ───────────────────────────── */
/* p11_utils.c requires p11_context.h but it is not used here */

int main(void)
{
    TEST_SUITE("P11RvToSecStatus — full CK_RV → SECURITY_STATUS mapping");

    /* Documented standard cases */
    ASSERT_EQ("CKR_OK → ERROR_SUCCESS",
        P11RvToSecStatus(CKR_OK), (SECURITY_STATUS)ERROR_SUCCESS);

    ASSERT_EQ("CKR_HOST_MEMORY → NTE_NO_MEMORY",
        P11RvToSecStatus(CKR_HOST_MEMORY), (SECURITY_STATUS)NTE_NO_MEMORY);

    ASSERT_EQ("CKR_ARGUMENTS_BAD → NTE_INVALID_PARAMETER",
        P11RvToSecStatus(CKR_ARGUMENTS_BAD), (SECURITY_STATUS)NTE_INVALID_PARAMETER);

    ASSERT_EQ("CKR_BUFFER_TOO_SMALL → NTE_BUFFER_TOO_SMALL",
        P11RvToSecStatus(CKR_BUFFER_TOO_SMALL), (SECURITY_STATUS)NTE_BUFFER_TOO_SMALL);

    ASSERT_EQ("CKR_FUNCTION_NOT_SUPPORTED → NTE_NOT_SUPPORTED",
        P11RvToSecStatus(CKR_FUNCTION_NOT_SUPPORTED), (SECURITY_STATUS)NTE_NOT_SUPPORTED);

    ASSERT_EQ("CKR_KEY_HANDLE_INVALID → NTE_BAD_KEY",
        P11RvToSecStatus(CKR_KEY_HANDLE_INVALID), (SECURITY_STATUS)NTE_BAD_KEY);

    ASSERT_EQ("CKR_KEY_SIZE_RANGE → NTE_BAD_LEN",
        P11RvToSecStatus(CKR_KEY_SIZE_RANGE), (SECURITY_STATUS)NTE_BAD_LEN);

    ASSERT_EQ("CKR_KEY_TYPE_INCONSISTENT → NTE_BAD_ALGID",
        P11RvToSecStatus(CKR_KEY_TYPE_INCONSISTENT), (SECURITY_STATUS)NTE_BAD_ALGID);

    ASSERT_EQ("CKR_MECHANISM_INVALID → NTE_BAD_ALGID",
        P11RvToSecStatus(CKR_MECHANISM_INVALID), (SECURITY_STATUS)NTE_BAD_ALGID);

    ASSERT_EQ("CKR_MECHANISM_PARAM_INVALID → NTE_BAD_ALGID",
        P11RvToSecStatus(CKR_MECHANISM_PARAM_INVALID), (SECURITY_STATUS)NTE_BAD_ALGID);

    ASSERT_EQ("CKR_OBJECT_HANDLE_INVALID → NTE_BAD_KEY",
        P11RvToSecStatus(CKR_OBJECT_HANDLE_INVALID), (SECURITY_STATUS)NTE_BAD_KEY);

    ASSERT_EQ("CKR_PIN_INCORRECT → NTE_BAD_KEYSET_PARAM",
        P11RvToSecStatus(CKR_PIN_INCORRECT), (SECURITY_STATUS)NTE_BAD_KEYSET_PARAM);

    ASSERT_EQ("CKR_PIN_LOCKED → NTE_BAD_KEYSET_PARAM",
        P11RvToSecStatus(CKR_PIN_LOCKED), (SECURITY_STATUS)NTE_BAD_KEYSET_PARAM);

    ASSERT_EQ("CKR_SESSION_HANDLE_INVALID → NTE_FAIL",
        P11RvToSecStatus(CKR_SESSION_HANDLE_INVALID), (SECURITY_STATUS)NTE_FAIL);

    ASSERT_EQ("CKR_SIGNATURE_INVALID → NTE_BAD_SIGNATURE",
        P11RvToSecStatus(CKR_SIGNATURE_INVALID), (SECURITY_STATUS)NTE_BAD_SIGNATURE);

    ASSERT_EQ("CKR_SIGNATURE_LEN_RANGE → NTE_BAD_LEN",
        P11RvToSecStatus(CKR_SIGNATURE_LEN_RANGE), (SECURITY_STATUS)NTE_BAD_LEN);

    ASSERT_EQ("CKR_TOKEN_NOT_PRESENT → NTE_NO_KEY",
        P11RvToSecStatus(CKR_TOKEN_NOT_PRESENT), (SECURITY_STATUS)NTE_NO_KEY);

    ASSERT_EQ("CKR_USER_NOT_LOGGED_IN → NTE_BAD_KEYSET_PARAM",
        P11RvToSecStatus(CKR_USER_NOT_LOGGED_IN), (SECURITY_STATUS)NTE_BAD_KEYSET_PARAM);

    ASSERT_EQ("CKR_KEY_UNEXTRACTABLE → NTE_NOT_SUPPORTED",
        P11RvToSecStatus(CKR_KEY_UNEXTRACTABLE), (SECURITY_STATUS)NTE_NOT_SUPPORTED);

    ASSERT_EQ("CKR_CRYPTOKI_NOT_INITIALIZED → NTE_FAIL",
        P11RvToSecStatus(CKR_CRYPTOKI_NOT_INITIALIZED), (SECURITY_STATUS)NTE_FAIL);

    /* Default case (unlisted code) */
    ASSERT_EQ("Unknown code 0xDEADBEEF → NTE_FAIL",
        P11RvToSecStatus(0xDEADBEEFUL), (SECURITY_STATUS)NTE_FAIL);

    ASSERT_EQ("CKR_GENERAL_ERROR → NTE_FAIL",
        P11RvToSecStatus(CKR_GENERAL_ERROR), (SECURITY_STATUS)NTE_FAIL);

    ASSERT_EQ("CKR_FUNCTION_FAILED → NTE_FAIL",
        P11RvToSecStatus(CKR_FUNCTION_FAILED), (SECURITY_STATUS)NTE_FAIL);

    ASSERT_EQ("CKR_DEVICE_ERROR → NTE_FAIL",
        P11RvToSecStatus(CKR_DEVICE_ERROR), (SECURITY_STATUS)NTE_FAIL);

    ASSERT_EQ("CKR_DATA_INVALID → NTE_FAIL",
        P11RvToSecStatus(CKR_DATA_INVALID), (SECURITY_STATUS)NTE_FAIL);

    /* Symmetric property: ERROR_SUCCESS if and only if CKR_OK */
    ASSERT("Only CKR_OK gives ERROR_SUCCESS",
        P11RvToSecStatus(CKR_OK) == ERROR_SUCCESS &&
        P11RvToSecStatus(CKR_GENERAL_ERROR) != ERROR_SUCCESS);

    TEST_REPORT();
    TEST_EXIT();
}
